" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Mensch-Regular:h11            " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=light              " Background.
set lines=25 columns=100          " Window dimensions.

set guioptions-=r                 " Don't show right scrollbar

colorscheme vividchalk
set linespace=3

let g:bufExplorerShowRelativePath=1

set tabstop=2
set shiftwidth=2
set si
set spell
set nowrap
